version: '3'
services:
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.7.8-management
    environment:
      RABBITMQ_DEFAULT_USER: rebbitmq
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: dev_vhost
    ports:
      - "5672:5672"
      - "15672:15672"
