version: '3'
services:
  bot:
    restart: always
    image: username502/vsong_bot:latest
    environment:
      - DEBUG
      - WORKERS_NUM

      - BOT_SECRET_URL
      - BOT_TOKEN
      - BOT_WEB_HOOK

      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_POST
      - POSTGRES_DB

      - SENTRY_KEY

      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST
      - RABBITMQ_SSL
      - RABBITMQ_QUERY
      - RABBITMQ_EXCHANGE

      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_END_POINT_URL
      - AWS_REGION_NAME
      - AWS_BUCKET

      - VK_LOGIN
      - VK_PASSWORD
      - VK_APP_ID

      - PROXY_USER
      - PROXY_PASSWORD
      - PROXY_IP
      - PROXY_PORT
    links:
      - postgres:postgres
      - rabbitmq:rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    expose:
      - "8000"
    ports:
      - "8000"
  postgres:
    restart: always
    image: postgres:11.1
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.7.8-management
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST
    ports:
      - "5672:5672"
      - "15672:15672"
  nginx:
      image: umputun/nginx-le:latest
      hostname: nginx
      restart: always
      container_name: nginx
      volumes:
          - ./etc/ssl:/etc/nginx/ssl
          - ./.nginx/app.conf:/etc/nginx/service.conf
      ports:
          - "80:80"
          - "443:443"
          - "8443:8443"
      environment:
          - TZ=GMT
          - LETSENCRYPT=true
          - LE_EMAIL=skar404@gamil.com
          - LE_FQDN=bot.guser.ru
