"""update s3_url

Revision ID: 9fea05a13c23
Revises: 84c6edb9a2f7
Create Date: 2019-01-21 23:01:16.550478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fea05a13c23'
down_revision = '84c6edb9a2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 's3_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 's3_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
