"""init

Revision ID: 470dc509cc37
Revises: 
Create Date: 2019-01-07 01:12:11.287472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470dc509cc37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=255), nullable=True),
    sa.Column('v_url', sa.String(length=255), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_info',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=50), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('users_stats',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_user', sa.Integer(), nullable=True),
    sa.Column('is_music', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['is_music'], ['music.id'], ),
    sa.ForeignKeyConstraint(['is_user'], ['users_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_stats')
    op.drop_table('users_info')
    op.drop_table('music')
    # ### end Alembic commands ###
