"""update index music

Revision ID: 317ebbe6163a
Revises: 9fea05a13c23
Create Date: 2019-01-23 00:07:23.659352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317ebbe6163a'
down_revision = '9fea05a13c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_music_artist'), 'music', ['artist'], unique=False)
    op.create_index(op.f('ix_music_owner_id'), 'music', ['owner_id'], unique=False)
    op.create_index(op.f('ix_music_time_created'), 'music', ['time_created'], unique=False)
    op.create_index(op.f('ix_music_title'), 'music', ['title'], unique=False)
    op.create_index(op.f('ix_music_vk_id'), 'music', ['vk_id'], unique=False)
    op.create_index('ui_music_model_id_owner_id_duration', 'music', ['vk_id', 'owner_id', 'artist', 'title', 'duration'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ui_music_model_id_owner_id_duration', table_name='music')
    op.drop_index(op.f('ix_music_vk_id'), table_name='music')
    op.drop_index(op.f('ix_music_title'), table_name='music')
    op.drop_index(op.f('ix_music_time_created'), table_name='music')
    op.drop_index(op.f('ix_music_owner_id'), table_name='music')
    op.drop_index(op.f('ix_music_artist'), table_name='music')
    # ### end Alembic commands ###
