"""update music model

Revision ID: 84c6edb9a2f7
Revises: e35820f394c7
Create Date: 2019-01-18 01:40:16.824617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c6edb9a2f7'
down_revision = 'e35820f394c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('music', sa.Column('vk_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'vk_id')
    op.drop_column('music', 'owner_id')
    # ### end Alembic commands ###
